// Helper: switch between screens
function showScreen(id) {
  document.querySelectorAll(".screen").forEach((s) => s.classList.remove("active"));
  document.getElementById(id).classList.add("active");
}

// LOGIN LOGIC (dummy)
const loginButton = document.getElementById("login-button");
const loginError = document.getElementById("login-error");

loginButton.addEventListener("click", () => {
  const email = document.getElementById("login-email").value.trim();
  const password = document.getElementById("login-password").value.trim();

  if (!email || !password) {
    loginError.textContent = "Please enter both email and password.";
    return;
  }

  // In the real app, this is where Firebase Auth is called.
  loginError.textContent = "";
  showScreen("screen-2fa");
});

// 2FA LOGIC (dummy: correct code = 123456)
const verify2FAButton = document.getElementById("verify-2fa-button");
const twofaError = document.getElementById("twofa-error");
const backToLoginButton = document.getElementById("back-to-login-button");

verify2FAButton.addEventListener("click", () => {
  const code = document.getElementById("code-2fa").value.trim();
  if (code === "123456") {
    twofaError.textContent = "";
    showScreen("screen-resume");
  } else {
    twofaError.textContent = "Invalid code. Use 123456 for the demo.";
  }
});

backToLoginButton.addEventListener("click", () => {
  showScreen("screen-login");
});

// LOGOUT
document.getElementById("logout-button").addEventListener("click", () => {
  // Clear fields for demo cleanliness
  document.getElementById("login-email").value = "";
  document.getElementById("login-password").value = "";
  document.getElementById("code-2fa").value = "";
  document.getElementById("resume-file").value = "";
  document.getElementById("resume-error").textContent = "";
  document.getElementById("feedback-text").innerHTML = "";
  document.getElementById("feedback-container").classList.add("hidden");

  showScreen("screen-login");
});

// AI FEEDBACK (mocked GPT behavior)
const aiButton = document.getElementById("ai-feedback-button");
const feedbackContainer = document.getElementById("feedback-container");
const feedbackText = document.getElementById("feedback-text");
const resumeFileInput = document.getElementById("resume-file");
const resumeError = document.getElementById("resume-error");

aiButton.addEventListener("click", () => {
  const file = resumeFileInput.files[0];

  if (!file) {
    resumeError.textContent = "Please upload a resume file before requesting feedback.";
    return;
  }

  resumeError.textContent = "";
  aiButton.disabled = true;
  aiButton.textContent = "Analyzing with AI...";

  // Simulate network delay and AI processing
  setTimeout(() => {
    // In the real system, this is where a backend would call GPT with the file content.
    const mockFeedbackHtml = `
      <p class="feedback-intro">
        Here's a high-level AI-style review of <strong>${file.name}</strong>.
      </p>

      <h4>Strengths</h4>
      <ul class="feedback-list">
        <li>Clear academic background and relevant technical skills.</li>
        <li>Concrete project or work experience that shows initiative.</li>
        <li>Good use of action verbs and concise bullet points.</li>
      </ul>

      <h4>Areas for Improvement</h4>
      <ul class="feedback-list">
        <li>Add more measurable outcomes (e.g., “improved X by 20%”).</li>
        <li>Move your most impressive experiences higher on the page.</li>
        <li>Tailor your bullets toward specific roles (data, software, etc.).</li>
      </ul>

      <p class="feedback-note">
        Ethical note: This feedback is generated by an AI-style system in a demo environment.
        Before making major career decisions, you should review it with a human advisor or
        career counselor.
      </p>
    `;

    feedbackText.innerHTML = mockFeedbackHtml;
    feedbackContainer.classList.remove("hidden");

    aiButton.disabled = false;
    aiButton.textContent = "Get AI Feedback";
  }, 1000);
});

// Initialize: show login screen
showScreen("screen-login");